-- FastapiAdmin DDL — PostgreSQL
-- 用法: psql -U postgres -f fastapiadmin_ddl.sql

-- CREATE DATABASE fastapiadmin WITH ENCODING 'UTF8';
\c fastapiadmin

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

DROP TABLE IF EXISTS sys_tenant;
CREATE TABLE IF NOT EXISTS sys_tenant (
  name varchar(100) NOT NULL,
  code varchar(100) NOT NULL,
  start_time timestamp DEFAULT NULL,
  end_time timestamp DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  CONSTRAINT sys_tenant_pkey PRIMARY KEY (id),
  CONSTRAINT name UNIQUE (name),
  CONSTRAINT code UNIQUE (code),
  CONSTRAINT ix_sys_tenant_uuid UNIQUE (uuid)
);
CREATE INDEX IF NOT EXISTS ix_sys_tenant_is_deleted ON sys_tenant (is_deleted);
CREATE INDEX IF NOT EXISTS ix_sys_tenant_status ON sys_tenant (status);
CREATE INDEX IF NOT EXISTS ix_sys_tenant_created_time ON sys_tenant (created_time);
CREATE INDEX IF NOT EXISTS ix_sys_tenant_deleted_time ON sys_tenant (deleted_time);
CREATE INDEX IF NOT EXISTS ix_sys_tenant_updated_time ON sys_tenant (updated_time);
COMMENT ON TABLE sys_tenant IS '租户表';
COMMENT ON COLUMN sys_tenant.name IS '租户名称';
COMMENT ON COLUMN sys_tenant.code IS '租户编码';
COMMENT ON COLUMN sys_tenant.start_time IS '开始时间';
COMMENT ON COLUMN sys_tenant.end_time IS '结束时间';
COMMENT ON COLUMN sys_tenant.id IS '主键ID';
COMMENT ON COLUMN sys_tenant.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_tenant.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_tenant.description IS '备注/描述';
COMMENT ON COLUMN sys_tenant.created_time IS '创建时间';
COMMENT ON COLUMN sys_tenant.updated_time IS '更新时间';
COMMENT ON COLUMN sys_tenant.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_tenant.deleted_time IS '删除时间';

DROP TABLE IF EXISTS sys_dept;
CREATE TABLE IF NOT EXISTS sys_dept (
  name varchar(64) NOT NULL,
  "order" integer NOT NULL,
  code varchar(16) NOT NULL,
  leader varchar(32) DEFAULT NULL,
  phone varchar(11) DEFAULT NULL,
  email varchar(64) DEFAULT NULL,
  parent_id integer DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  CONSTRAINT sys_dept_pkey PRIMARY KEY (id),
  CONSTRAINT code UNIQUE (code),
  CONSTRAINT ix_sys_dept_uuid UNIQUE (uuid),
  CONSTRAINT sys_dept_ibfk_1 FOREIGN KEY (parent_id) REFERENCES sys_dept(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_sys_dept_updated_time ON sys_dept (updated_time);
CREATE INDEX IF NOT EXISTS ix_sys_dept_parent_id ON sys_dept (parent_id);
CREATE INDEX IF NOT EXISTS ix_sys_dept_is_deleted ON sys_dept (is_deleted);
CREATE INDEX IF NOT EXISTS ix_sys_dept_status ON sys_dept (status);
CREATE INDEX IF NOT EXISTS ix_sys_dept_created_time ON sys_dept (created_time);
CREATE INDEX IF NOT EXISTS ix_sys_dept_deleted_time ON sys_dept (deleted_time);
COMMENT ON TABLE sys_dept IS '部门表';
COMMENT ON COLUMN sys_dept.name IS '部门名称';
COMMENT ON COLUMN sys_dept.order IS '显示排序';
COMMENT ON COLUMN sys_dept.code IS '部门编码';
COMMENT ON COLUMN sys_dept.leader IS '部门负责人';
COMMENT ON COLUMN sys_dept.phone IS '手机';
COMMENT ON COLUMN sys_dept.email IS '邮箱';
COMMENT ON COLUMN sys_dept.parent_id IS '父级部门ID';
COMMENT ON COLUMN sys_dept.id IS '主键ID';
COMMENT ON COLUMN sys_dept.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_dept.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_dept.description IS '备注/描述';
COMMENT ON COLUMN sys_dept.created_time IS '创建时间';
COMMENT ON COLUMN sys_dept.updated_time IS '更新时间';
COMMENT ON COLUMN sys_dept.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_dept.deleted_time IS '删除时间';

DROP TABLE IF EXISTS sys_menu;
CREATE TABLE IF NOT EXISTS sys_menu (
  name varchar(50) NOT NULL,
  type integer NOT NULL,
  "order" integer NOT NULL,
  permission varchar(100) DEFAULT NULL,
  icon varchar(50) DEFAULT NULL,
  route_name varchar(100) DEFAULT NULL,
  route_path varchar(200) DEFAULT NULL,
  component_path varchar(200) DEFAULT NULL,
  redirect varchar(200) DEFAULT NULL,
  hidden smallint NOT NULL DEFAULT 0,
  keep_alive smallint NOT NULL DEFAULT 0,
  always_show smallint NOT NULL DEFAULT 0,
  title varchar(50) DEFAULT NULL,
  params jsonb DEFAULT NULL,
  affix smallint NOT NULL DEFAULT 0,
  client varchar(20) NOT NULL DEFAULT 'pc',
  parent_id integer DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  CONSTRAINT sys_menu_pkey PRIMARY KEY (id),
  CONSTRAINT ix_sys_menu_uuid UNIQUE (uuid),
  CONSTRAINT sys_menu_ibfk_1 FOREIGN KEY (parent_id) REFERENCES sys_menu(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_sys_menu_deleted_time ON sys_menu (deleted_time);
CREATE INDEX IF NOT EXISTS ix_sys_menu_parent_id ON sys_menu (parent_id);
CREATE INDEX IF NOT EXISTS ix_sys_menu_updated_time ON sys_menu (updated_time);
CREATE INDEX IF NOT EXISTS ix_sys_menu_is_deleted ON sys_menu (is_deleted);
CREATE INDEX IF NOT EXISTS ix_sys_menu_status ON sys_menu (status);
CREATE INDEX IF NOT EXISTS ix_sys_menu_created_time ON sys_menu (created_time);
COMMENT ON TABLE sys_menu IS '菜单表';
COMMENT ON COLUMN sys_menu.name IS '菜单名称';
COMMENT ON COLUMN sys_menu.type IS '菜单类型(1:目录 2:菜单 3:按钮/权限 4:链接)';
COMMENT ON COLUMN sys_menu.order IS '显示排序';
COMMENT ON COLUMN sys_menu.permission IS '权限标识(如:module_system:user:query)';
COMMENT ON COLUMN sys_menu.icon IS '菜单图标';
COMMENT ON COLUMN sys_menu.route_name IS '路由名称';
COMMENT ON COLUMN sys_menu.route_path IS '路由路径';
COMMENT ON COLUMN sys_menu.component_path IS '组件路径';
COMMENT ON COLUMN sys_menu.redirect IS '重定向地址';
COMMENT ON COLUMN sys_menu.hidden IS '是否隐藏(True:隐藏 False:显示)';
COMMENT ON COLUMN sys_menu.keep_alive IS '是否缓存(True:是 False:否)';
COMMENT ON COLUMN sys_menu.always_show IS '是否始终显示(True:是 False:否)';
COMMENT ON COLUMN sys_menu.title IS '菜单标题';
COMMENT ON COLUMN sys_menu.params IS '路由参数(JSON对象)';
COMMENT ON COLUMN sys_menu.affix IS '是否固定标签页(True:是 False:否)';
COMMENT ON COLUMN sys_menu.client IS '终端(pc:管理端桌面 app:移动端)';
COMMENT ON COLUMN sys_menu.parent_id IS '父菜单ID';
COMMENT ON COLUMN sys_menu.id IS '主键ID';
COMMENT ON COLUMN sys_menu.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_menu.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_menu.description IS '备注/描述';
COMMENT ON COLUMN sys_menu.created_time IS '创建时间';
COMMENT ON COLUMN sys_menu.updated_time IS '更新时间';
COMMENT ON COLUMN sys_menu.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_menu.deleted_time IS '删除时间';

DROP TABLE IF EXISTS sys_role;
CREATE TABLE IF NOT EXISTS sys_role (
  name varchar(64) NOT NULL,
  code varchar(16) NOT NULL,
  "order" integer NOT NULL,
  data_scope integer NOT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  CONSTRAINT sys_role_pkey PRIMARY KEY (id),
  CONSTRAINT code UNIQUE (code),
  CONSTRAINT ix_sys_role_uuid UNIQUE (uuid)
);
CREATE INDEX IF NOT EXISTS ix_sys_role_is_deleted ON sys_role (is_deleted);
CREATE INDEX IF NOT EXISTS ix_sys_role_status ON sys_role (status);
CREATE INDEX IF NOT EXISTS ix_sys_role_created_time ON sys_role (created_time);
CREATE INDEX IF NOT EXISTS ix_sys_role_deleted_time ON sys_role (deleted_time);
CREATE INDEX IF NOT EXISTS ix_sys_role_updated_time ON sys_role (updated_time);
COMMENT ON TABLE sys_role IS '角色表';
COMMENT ON COLUMN sys_role.name IS '角色名称';
COMMENT ON COLUMN sys_role.code IS '角色编码';
COMMENT ON COLUMN sys_role.order IS '显示排序';
COMMENT ON COLUMN sys_role.data_scope IS '数据权限范围(1:仅本人 2:本部门 3:本部门及以下 4:全部 5:自定义)';
COMMENT ON COLUMN sys_role.id IS '主键ID';
COMMENT ON COLUMN sys_role.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_role.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_role.description IS '备注/描述';
COMMENT ON COLUMN sys_role.created_time IS '创建时间';
COMMENT ON COLUMN sys_role.updated_time IS '更新时间';
COMMENT ON COLUMN sys_role.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_role.deleted_time IS '删除时间';

DROP TABLE IF EXISTS sys_dict_type;
CREATE TABLE IF NOT EXISTS sys_dict_type (
  dict_name varchar(64) NOT NULL,
  dict_type varchar(255) NOT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  CONSTRAINT sys_dict_type_pkey PRIMARY KEY (id),
  CONSTRAINT dict_type UNIQUE (dict_type),
  CONSTRAINT ix_sys_dict_type_uuid UNIQUE (uuid)
);
CREATE INDEX IF NOT EXISTS ix_sys_dict_type_updated_time ON sys_dict_type (updated_time);
CREATE INDEX IF NOT EXISTS ix_sys_dict_type_is_deleted ON sys_dict_type (is_deleted);
CREATE INDEX IF NOT EXISTS ix_sys_dict_type_status ON sys_dict_type (status);
CREATE INDEX IF NOT EXISTS ix_sys_dict_type_deleted_time ON sys_dict_type (deleted_time);
CREATE INDEX IF NOT EXISTS ix_sys_dict_type_created_time ON sys_dict_type (created_time);
COMMENT ON TABLE sys_dict_type IS '字典类型表';
COMMENT ON COLUMN sys_dict_type.dict_name IS '字典名称';
COMMENT ON COLUMN sys_dict_type.dict_type IS '字典类型';
COMMENT ON COLUMN sys_dict_type.id IS '主键ID';
COMMENT ON COLUMN sys_dict_type.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_dict_type.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_dict_type.description IS '备注/描述';
COMMENT ON COLUMN sys_dict_type.created_time IS '创建时间';
COMMENT ON COLUMN sys_dict_type.updated_time IS '更新时间';
COMMENT ON COLUMN sys_dict_type.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_dict_type.deleted_time IS '删除时间';

DROP TABLE IF EXISTS sys_user;
CREATE TABLE IF NOT EXISTS sys_user (
  username varchar(64) NOT NULL,
  password varchar(255) NOT NULL,
  name varchar(32) NOT NULL,
  mobile varchar(11) DEFAULT NULL,
  email varchar(64) DEFAULT NULL,
  gender varchar(1) DEFAULT NULL,
  avatar varchar(255) DEFAULT NULL,
  is_superuser smallint NOT NULL DEFAULT 0,
  last_login timestamp DEFAULT NULL,
  gitee_login varchar(32) DEFAULT NULL,
  github_login varchar(32) DEFAULT NULL,
  wx_login varchar(32) DEFAULT NULL,
  qq_login varchar(32) DEFAULT NULL,
  dept_id integer DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  tenant_id integer NOT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT sys_user_pkey PRIMARY KEY (id),
  CONSTRAINT username UNIQUE (username),
  CONSTRAINT ix_sys_user_uuid UNIQUE (uuid),
  CONSTRAINT mobile UNIQUE (mobile),
  CONSTRAINT email UNIQUE (email),
  CONSTRAINT sys_user_ibfk_1 FOREIGN KEY (dept_id) REFERENCES sys_dept(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT sys_user_ibfk_2 FOREIGN KEY (tenant_id) REFERENCES sys_tenant(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT sys_user_ibfk_3 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT sys_user_ibfk_4 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT sys_user_ibfk_5 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_sys_user_created_time ON sys_user (created_time);
CREATE INDEX IF NOT EXISTS ix_sys_user_deleted_time ON sys_user (deleted_time);
CREATE INDEX IF NOT EXISTS ix_sys_user_tenant_id ON sys_user (tenant_id);
CREATE INDEX IF NOT EXISTS ix_sys_user_deleted_id ON sys_user (deleted_id);
CREATE INDEX IF NOT EXISTS ix_sys_user_created_id ON sys_user (created_id);
CREATE INDEX IF NOT EXISTS ix_sys_user_updated_time ON sys_user (updated_time);
CREATE INDEX IF NOT EXISTS ix_sys_user_dept_id ON sys_user (dept_id);
CREATE INDEX IF NOT EXISTS ix_sys_user_updated_id ON sys_user (updated_id);
CREATE INDEX IF NOT EXISTS ix_sys_user_status ON sys_user (status);
CREATE INDEX IF NOT EXISTS ix_sys_user_is_deleted ON sys_user (is_deleted);
COMMENT ON TABLE sys_user IS '用户表';
COMMENT ON COLUMN sys_user.username IS '用户名/登录账号';
COMMENT ON COLUMN sys_user.password IS '密码哈希';
COMMENT ON COLUMN sys_user.name IS '昵称';
COMMENT ON COLUMN sys_user.mobile IS '手机号';
COMMENT ON COLUMN sys_user.email IS '邮箱';
COMMENT ON COLUMN sys_user.gender IS '性别(0:男 1:女 2:未知)';
COMMENT ON COLUMN sys_user.avatar IS '头像URL地址';
COMMENT ON COLUMN sys_user.is_superuser IS '是否超管';
COMMENT ON COLUMN sys_user.last_login IS '最后登录时间';
COMMENT ON COLUMN sys_user.gitee_login IS 'Gitee登录';
COMMENT ON COLUMN sys_user.github_login IS 'Github登录';
COMMENT ON COLUMN sys_user.wx_login IS '微信登录';
COMMENT ON COLUMN sys_user.qq_login IS 'QQ登录';
COMMENT ON COLUMN sys_user.dept_id IS '部门ID';
COMMENT ON COLUMN sys_user.id IS '主键ID';
COMMENT ON COLUMN sys_user.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_user.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_user.description IS '备注/描述';
COMMENT ON COLUMN sys_user.created_time IS '创建时间';
COMMENT ON COLUMN sys_user.updated_time IS '更新时间';
COMMENT ON COLUMN sys_user.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_user.deleted_time IS '删除时间';
COMMENT ON COLUMN sys_user.tenant_id IS '租户ID';
COMMENT ON COLUMN sys_user.created_id IS '创建人ID';
COMMENT ON COLUMN sys_user.updated_id IS '更新人ID';
COMMENT ON COLUMN sys_user.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS sys_dict_data;
CREATE TABLE IF NOT EXISTS sys_dict_data (
  dict_sort integer NOT NULL,
  dict_label varchar(255) NOT NULL,
  dict_value varchar(255) NOT NULL,
  css_class varchar(255) DEFAULT NULL,
  list_class varchar(255) DEFAULT NULL,
  is_default smallint NOT NULL DEFAULT 0,
  dict_type varchar(255) NOT NULL,
  dict_type_id integer NOT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  CONSTRAINT sys_dict_data_pkey PRIMARY KEY (id),
  CONSTRAINT ix_sys_dict_data_uuid UNIQUE (uuid),
  CONSTRAINT sys_dict_data_ibfk_1 FOREIGN KEY (dict_type_id) REFERENCES sys_dict_type(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS dict_type_id ON sys_dict_data (dict_type_id);
CREATE INDEX IF NOT EXISTS ix_sys_dict_data_created_time ON sys_dict_data (created_time);
CREATE INDEX IF NOT EXISTS ix_sys_dict_data_deleted_time ON sys_dict_data (deleted_time);
CREATE INDEX IF NOT EXISTS ix_sys_dict_data_status ON sys_dict_data (status);
CREATE INDEX IF NOT EXISTS ix_sys_dict_data_updated_time ON sys_dict_data (updated_time);
CREATE INDEX IF NOT EXISTS ix_sys_dict_data_is_deleted ON sys_dict_data (is_deleted);
COMMENT ON TABLE sys_dict_data IS '字典数据表';
COMMENT ON COLUMN sys_dict_data.dict_sort IS '字典排序';
COMMENT ON COLUMN sys_dict_data.dict_label IS '字典标签';
COMMENT ON COLUMN sys_dict_data.dict_value IS '字典键值';
COMMENT ON COLUMN sys_dict_data.css_class IS '样式属性（其他样式扩展）';
COMMENT ON COLUMN sys_dict_data.list_class IS '表格回显样式';
COMMENT ON COLUMN sys_dict_data.is_default IS '是否默认（True是 False否）';
COMMENT ON COLUMN sys_dict_data.dict_type IS '字典类型';
COMMENT ON COLUMN sys_dict_data.dict_type_id IS '字典类型ID';
COMMENT ON COLUMN sys_dict_data.id IS '主键ID';
COMMENT ON COLUMN sys_dict_data.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_dict_data.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_dict_data.description IS '备注/描述';
COMMENT ON COLUMN sys_dict_data.created_time IS '创建时间';
COMMENT ON COLUMN sys_dict_data.updated_time IS '更新时间';
COMMENT ON COLUMN sys_dict_data.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_dict_data.deleted_time IS '删除时间';

DROP TABLE IF EXISTS sys_param;
CREATE TABLE IF NOT EXISTS sys_param (
  config_name varchar(64) NOT NULL,
  config_key varchar(500) NOT NULL,
  config_value varchar(500) DEFAULT NULL,
  config_type smallint DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  CONSTRAINT sys_param_pkey PRIMARY KEY (id),
  CONSTRAINT ix_sys_param_uuid UNIQUE (uuid)
);
CREATE INDEX IF NOT EXISTS ix_sys_param_updated_time ON sys_param (updated_time);
CREATE INDEX IF NOT EXISTS ix_sys_param_is_deleted ON sys_param (is_deleted);
CREATE INDEX IF NOT EXISTS ix_sys_param_status ON sys_param (status);
CREATE INDEX IF NOT EXISTS ix_sys_param_created_time ON sys_param (created_time);
CREATE INDEX IF NOT EXISTS ix_sys_param_deleted_time ON sys_param (deleted_time);
COMMENT ON TABLE sys_param IS '系统参数表';
COMMENT ON COLUMN sys_param.config_name IS '参数名称';
COMMENT ON COLUMN sys_param.config_key IS '参数键名';
COMMENT ON COLUMN sys_param.config_value IS '参数键值';
COMMENT ON COLUMN sys_param.config_type IS '系统内置(True:是 False:否)';
COMMENT ON COLUMN sys_param.id IS '主键ID';
COMMENT ON COLUMN sys_param.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_param.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_param.description IS '备注/描述';
COMMENT ON COLUMN sys_param.created_time IS '创建时间';
COMMENT ON COLUMN sys_param.updated_time IS '更新时间';
COMMENT ON COLUMN sys_param.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_param.deleted_time IS '删除时间';

DROP TABLE IF EXISTS sys_position;
CREATE TABLE IF NOT EXISTS sys_position (
  name varchar(64) NOT NULL,
  "order" integer NOT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT sys_position_pkey PRIMARY KEY (id),
  CONSTRAINT ix_sys_position_uuid UNIQUE (uuid),
  CONSTRAINT sys_position_ibfk_1 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT sys_position_ibfk_2 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT sys_position_ibfk_3 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_sys_position_created_id ON sys_position (created_id);
CREATE INDEX IF NOT EXISTS ix_sys_position_updated_id ON sys_position (updated_id);
CREATE INDEX IF NOT EXISTS ix_sys_position_updated_time ON sys_position (updated_time);
CREATE INDEX IF NOT EXISTS ix_sys_position_is_deleted ON sys_position (is_deleted);
CREATE INDEX IF NOT EXISTS ix_sys_position_status ON sys_position (status);
CREATE INDEX IF NOT EXISTS ix_sys_position_deleted_id ON sys_position (deleted_id);
CREATE INDEX IF NOT EXISTS ix_sys_position_created_time ON sys_position (created_time);
CREATE INDEX IF NOT EXISTS ix_sys_position_deleted_time ON sys_position (deleted_time);
COMMENT ON TABLE sys_position IS '岗位表';
COMMENT ON COLUMN sys_position.name IS '岗位名称';
COMMENT ON COLUMN sys_position.order IS '显示排序';
COMMENT ON COLUMN sys_position.id IS '主键ID';
COMMENT ON COLUMN sys_position.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_position.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_position.description IS '备注/描述';
COMMENT ON COLUMN sys_position.created_time IS '创建时间';
COMMENT ON COLUMN sys_position.updated_time IS '更新时间';
COMMENT ON COLUMN sys_position.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_position.deleted_time IS '删除时间';
COMMENT ON COLUMN sys_position.created_id IS '创建人ID';
COMMENT ON COLUMN sys_position.updated_id IS '更新人ID';
COMMENT ON COLUMN sys_position.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS sys_user_roles;
CREATE TABLE IF NOT EXISTS sys_user_roles (
  user_id integer NOT NULL,
  role_id integer NOT NULL,
  CONSTRAINT sys_user_roles_ibfk_1 FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT sys_user_roles_ibfk_2 FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS role_id ON sys_user_roles (role_id);
COMMENT ON TABLE sys_user_roles IS '用户角色关联表';
COMMENT ON COLUMN sys_user_roles.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_roles.role_id IS '角色ID';

DROP TABLE IF EXISTS sys_user_positions;
CREATE TABLE IF NOT EXISTS sys_user_positions (
  user_id integer NOT NULL,
  position_id integer NOT NULL,
  CONSTRAINT sys_user_positions_ibfk_1 FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT sys_user_positions_ibfk_2 FOREIGN KEY (position_id) REFERENCES sys_position(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS position_id ON sys_user_positions (position_id);
COMMENT ON TABLE sys_user_positions IS '用户岗位关联表';
COMMENT ON COLUMN sys_user_positions.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_positions.position_id IS '岗位ID';

DROP TABLE IF EXISTS sys_role_depts;
CREATE TABLE IF NOT EXISTS sys_role_depts (
  role_id integer NOT NULL,
  dept_id integer NOT NULL,
  CONSTRAINT sys_role_depts_ibfk_1 FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT sys_role_depts_ibfk_2 FOREIGN KEY (dept_id) REFERENCES sys_dept(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS dept_id ON sys_role_depts (dept_id);
COMMENT ON TABLE sys_role_depts IS '角色部门关联表';
COMMENT ON COLUMN sys_role_depts.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_depts.dept_id IS '部门ID';

DROP TABLE IF EXISTS sys_role_menus;
CREATE TABLE IF NOT EXISTS sys_role_menus (
  role_id integer NOT NULL,
  menu_id integer NOT NULL,
  CONSTRAINT sys_role_menus_ibfk_1 FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT sys_role_menus_ibfk_2 FOREIGN KEY (menu_id) REFERENCES sys_menu(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS menu_id ON sys_role_menus (menu_id);
COMMENT ON TABLE sys_role_menus IS '角色菜单关联表';
COMMENT ON COLUMN sys_role_menus.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_menus.menu_id IS '菜单ID';

DROP TABLE IF EXISTS sys_log;
CREATE TABLE IF NOT EXISTS sys_log (
  type integer NOT NULL,
  request_path varchar(255) NOT NULL,
  request_method varchar(10) NOT NULL,
  request_payload text,
  request_ip varchar(50) DEFAULT NULL,
  login_location varchar(255) DEFAULT NULL,
  request_os varchar(64) DEFAULT NULL,
  request_browser varchar(64) DEFAULT NULL,
  response_code integer NOT NULL,
  response_json text,
  process_time varchar(20) DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT sys_log_pkey PRIMARY KEY (id),
  CONSTRAINT ix_sys_log_uuid UNIQUE (uuid),
  CONSTRAINT sys_log_ibfk_1 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT sys_log_ibfk_2 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT sys_log_ibfk_3 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_sys_log_updated_time ON sys_log (updated_time);
CREATE INDEX IF NOT EXISTS ix_sys_log_updated_id ON sys_log (updated_id);
CREATE INDEX IF NOT EXISTS ix_sys_log_deleted_id ON sys_log (deleted_id);
CREATE INDEX IF NOT EXISTS ix_sys_log_created_time ON sys_log (created_time);
CREATE INDEX IF NOT EXISTS ix_sys_log_deleted_time ON sys_log (deleted_time);
CREATE INDEX IF NOT EXISTS ix_sys_log_status ON sys_log (status);
CREATE INDEX IF NOT EXISTS ix_sys_log_is_deleted ON sys_log (is_deleted);
CREATE INDEX IF NOT EXISTS ix_sys_log_created_id ON sys_log (created_id);
COMMENT ON TABLE sys_log IS '系统日志表';
COMMENT ON COLUMN sys_log.type IS '日志类型(1登录日志 2操作日志)';
COMMENT ON COLUMN sys_log.request_path IS '请求路径';
COMMENT ON COLUMN sys_log.request_method IS '请求方式';
COMMENT ON COLUMN sys_log.request_payload IS '请求体';
COMMENT ON COLUMN sys_log.request_ip IS '请求IP地址';
COMMENT ON COLUMN sys_log.login_location IS '登录位置';
COMMENT ON COLUMN sys_log.request_os IS '操作系统';
COMMENT ON COLUMN sys_log.request_browser IS '浏览器';
COMMENT ON COLUMN sys_log.response_code IS '响应状态码';
COMMENT ON COLUMN sys_log.response_json IS '响应体';
COMMENT ON COLUMN sys_log.process_time IS '处理时间';
COMMENT ON COLUMN sys_log.id IS '主键ID';
COMMENT ON COLUMN sys_log.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_log.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_log.description IS '备注/描述';
COMMENT ON COLUMN sys_log.created_time IS '创建时间';
COMMENT ON COLUMN sys_log.updated_time IS '更新时间';
COMMENT ON COLUMN sys_log.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_log.deleted_time IS '删除时间';
COMMENT ON COLUMN sys_log.created_id IS '创建人ID';
COMMENT ON COLUMN sys_log.updated_id IS '更新人ID';
COMMENT ON COLUMN sys_log.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS sys_notice;
CREATE TABLE IF NOT EXISTS sys_notice (
  notice_title varchar(64) NOT NULL,
  notice_type varchar(1) NOT NULL,
  notice_content text,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT sys_notice_pkey PRIMARY KEY (id),
  CONSTRAINT ix_sys_notice_uuid UNIQUE (uuid),
  CONSTRAINT sys_notice_ibfk_1 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT sys_notice_ibfk_2 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT sys_notice_ibfk_3 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_sys_notice_updated_id ON sys_notice (updated_id);
CREATE INDEX IF NOT EXISTS ix_sys_notice_updated_time ON sys_notice (updated_time);
CREATE INDEX IF NOT EXISTS ix_sys_notice_is_deleted ON sys_notice (is_deleted);
CREATE INDEX IF NOT EXISTS ix_sys_notice_status ON sys_notice (status);
CREATE INDEX IF NOT EXISTS ix_sys_notice_deleted_id ON sys_notice (deleted_id);
CREATE INDEX IF NOT EXISTS ix_sys_notice_created_time ON sys_notice (created_time);
CREATE INDEX IF NOT EXISTS ix_sys_notice_deleted_time ON sys_notice (deleted_time);
CREATE INDEX IF NOT EXISTS ix_sys_notice_created_id ON sys_notice (created_id);
COMMENT ON TABLE sys_notice IS '通知公告表';
COMMENT ON COLUMN sys_notice.notice_title IS '公告标题';
COMMENT ON COLUMN sys_notice.notice_type IS '公告类型(1通知 2公告)';
COMMENT ON COLUMN sys_notice.notice_content IS '公告内容';
COMMENT ON COLUMN sys_notice.id IS '主键ID';
COMMENT ON COLUMN sys_notice.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN sys_notice.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN sys_notice.description IS '备注/描述';
COMMENT ON COLUMN sys_notice.created_time IS '创建时间';
COMMENT ON COLUMN sys_notice.updated_time IS '更新时间';
COMMENT ON COLUMN sys_notice.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN sys_notice.deleted_time IS '删除时间';
COMMENT ON COLUMN sys_notice.created_id IS '创建人ID';
COMMENT ON COLUMN sys_notice.updated_id IS '更新人ID';
COMMENT ON COLUMN sys_notice.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS app_portal;
CREATE TABLE IF NOT EXISTS app_portal (
  name varchar(64) NOT NULL,
  access_url varchar(500) NOT NULL,
  icon_url varchar(300) DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  tenant_id integer NOT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT app_portal_pkey PRIMARY KEY (id),
  CONSTRAINT ix_app_portal_uuid UNIQUE (uuid),
  CONSTRAINT app_portal_ibfk_1 FOREIGN KEY (tenant_id) REFERENCES sys_tenant(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT app_portal_ibfk_2 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT app_portal_ibfk_3 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT app_portal_ibfk_4 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_app_portal_tenant_id ON app_portal (tenant_id);
CREATE INDEX IF NOT EXISTS ix_app_portal_deleted_id ON app_portal (deleted_id);
CREATE INDEX IF NOT EXISTS ix_app_portal_created_id ON app_portal (created_id);
CREATE INDEX IF NOT EXISTS ix_app_portal_updated_time ON app_portal (updated_time);
CREATE INDEX IF NOT EXISTS ix_app_portal_is_deleted ON app_portal (is_deleted);
CREATE INDEX IF NOT EXISTS ix_app_portal_status ON app_portal (status);
CREATE INDEX IF NOT EXISTS ix_app_portal_updated_id ON app_portal (updated_id);
CREATE INDEX IF NOT EXISTS ix_app_portal_created_time ON app_portal (created_time);
CREATE INDEX IF NOT EXISTS ix_app_portal_deleted_time ON app_portal (deleted_time);
COMMENT ON TABLE app_portal IS '门户应用';
COMMENT ON COLUMN app_portal.name IS '应用名称';
COMMENT ON COLUMN app_portal.access_url IS '访问地址';
COMMENT ON COLUMN app_portal.icon_url IS '应用图标URL';
COMMENT ON COLUMN app_portal.id IS '主键ID';
COMMENT ON COLUMN app_portal.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN app_portal.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN app_portal.description IS '备注/描述';
COMMENT ON COLUMN app_portal.created_time IS '创建时间';
COMMENT ON COLUMN app_portal.updated_time IS '更新时间';
COMMENT ON COLUMN app_portal.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN app_portal.deleted_time IS '删除时间';
COMMENT ON COLUMN app_portal.tenant_id IS '租户ID';
COMMENT ON COLUMN app_portal.created_id IS '创建人ID';
COMMENT ON COLUMN app_portal.updated_id IS '更新人ID';
COMMENT ON COLUMN app_portal.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS gen_table;
CREATE TABLE IF NOT EXISTS gen_table (
  table_name varchar(200) NOT NULL,
  table_comment varchar(500) DEFAULT NULL,
  class_name varchar(100) NOT NULL,
  package_name varchar(100) DEFAULT NULL,
  module_name varchar(30) DEFAULT NULL,
  business_name varchar(30) DEFAULT NULL,
  function_name varchar(100) DEFAULT NULL,
  sub_table_name varchar(64) DEFAULT NULL,
  sub_table_fk_name varchar(64) DEFAULT NULL,
  parent_menu_id integer DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT gen_table_pkey PRIMARY KEY (id),
  CONSTRAINT ix_gen_table_uuid UNIQUE (uuid),
  CONSTRAINT gen_table_ibfk_1 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT gen_table_ibfk_2 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT gen_table_ibfk_3 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_gen_table_is_deleted ON gen_table (is_deleted);
CREATE INDEX IF NOT EXISTS ix_gen_table_status ON gen_table (status);
CREATE INDEX IF NOT EXISTS ix_gen_table_deleted_id ON gen_table (deleted_id);
CREATE INDEX IF NOT EXISTS ix_gen_table_created_time ON gen_table (created_time);
CREATE INDEX IF NOT EXISTS ix_gen_table_deleted_time ON gen_table (deleted_time);
CREATE INDEX IF NOT EXISTS ix_gen_table_created_id ON gen_table (created_id);
CREATE INDEX IF NOT EXISTS ix_gen_table_updated_id ON gen_table (updated_id);
CREATE INDEX IF NOT EXISTS ix_gen_table_updated_time ON gen_table (updated_time);
COMMENT ON TABLE gen_table IS '代码生成表';
COMMENT ON COLUMN gen_table.table_name IS '表名称';
COMMENT ON COLUMN gen_table.table_comment IS '表描述';
COMMENT ON COLUMN gen_table.class_name IS '实体类名称';
COMMENT ON COLUMN gen_table.package_name IS '生成包路径';
COMMENT ON COLUMN gen_table.module_name IS '生成模块名';
COMMENT ON COLUMN gen_table.business_name IS '生成业务名';
COMMENT ON COLUMN gen_table.function_name IS '生成功能名';
COMMENT ON COLUMN gen_table.sub_table_name IS '关联子表的表名';
COMMENT ON COLUMN gen_table.sub_table_fk_name IS '子表关联的外键名';
COMMENT ON COLUMN gen_table.parent_menu_id IS '父菜单ID';
COMMENT ON COLUMN gen_table.id IS '主键ID';
COMMENT ON COLUMN gen_table.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN gen_table.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN gen_table.description IS '备注/描述';
COMMENT ON COLUMN gen_table.created_time IS '创建时间';
COMMENT ON COLUMN gen_table.updated_time IS '更新时间';
COMMENT ON COLUMN gen_table.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN gen_table.deleted_time IS '删除时间';
COMMENT ON COLUMN gen_table.created_id IS '创建人ID';
COMMENT ON COLUMN gen_table.updated_id IS '更新人ID';
COMMENT ON COLUMN gen_table.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS gen_table_column;
CREATE TABLE IF NOT EXISTS gen_table_column (
  column_name varchar(200) NOT NULL,
  column_comment varchar(500) DEFAULT NULL,
  column_type varchar(100) NOT NULL,
  column_length varchar(50) DEFAULT NULL,
  column_default varchar(200) DEFAULT NULL,
  is_pk smallint NOT NULL DEFAULT 0,
  is_increment smallint NOT NULL DEFAULT 0,
  is_nullable smallint NOT NULL DEFAULT 1,
  is_unique smallint NOT NULL DEFAULT 0,
  python_type varchar(100) DEFAULT NULL,
  python_field varchar(200) DEFAULT NULL,
  is_insert smallint NOT NULL DEFAULT 1,
  is_edit smallint NOT NULL DEFAULT 1,
  is_list smallint NOT NULL DEFAULT 1,
  is_query smallint NOT NULL DEFAULT 0,
  query_type varchar(50) DEFAULT NULL,
  html_type varchar(100) DEFAULT NULL,
  dict_type varchar(200) DEFAULT NULL,
  sort integer NOT NULL,
  table_id integer NOT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT gen_table_column_pkey PRIMARY KEY (id),
  CONSTRAINT ix_gen_table_column_uuid UNIQUE (uuid),
  CONSTRAINT gen_table_column_ibfk_1 FOREIGN KEY (table_id) REFERENCES gen_table(id) ON DELETE CASCADE,
  CONSTRAINT gen_table_column_ibfk_2 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT gen_table_column_ibfk_3 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT gen_table_column_ibfk_4 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_gen_table_column_created_time ON gen_table_column (created_time);
CREATE INDEX IF NOT EXISTS ix_gen_table_column_status ON gen_table_column (status);
CREATE INDEX IF NOT EXISTS ix_gen_table_column_is_deleted ON gen_table_column (is_deleted);
CREATE INDEX IF NOT EXISTS ix_gen_table_column_updated_id ON gen_table_column (updated_id);
CREATE INDEX IF NOT EXISTS ix_gen_table_column_table_id ON gen_table_column (table_id);
CREATE INDEX IF NOT EXISTS ix_gen_table_column_created_id ON gen_table_column (created_id);
CREATE INDEX IF NOT EXISTS ix_gen_table_column_updated_time ON gen_table_column (updated_time);
CREATE INDEX IF NOT EXISTS ix_gen_table_column_deleted_time ON gen_table_column (deleted_time);
CREATE INDEX IF NOT EXISTS ix_gen_table_column_deleted_id ON gen_table_column (deleted_id);
COMMENT ON TABLE gen_table_column IS '代码生成表字段';
COMMENT ON COLUMN gen_table_column.column_name IS '列名称';
COMMENT ON COLUMN gen_table_column.column_comment IS '列描述';
COMMENT ON COLUMN gen_table_column.column_type IS '列类型';
COMMENT ON COLUMN gen_table_column.column_length IS '列长度';
COMMENT ON COLUMN gen_table_column.column_default IS '列默认值';
COMMENT ON COLUMN gen_table_column.is_pk IS '是否主键';
COMMENT ON COLUMN gen_table_column.is_increment IS '是否自增';
COMMENT ON COLUMN gen_table_column.is_nullable IS '是否允许为空';
COMMENT ON COLUMN gen_table_column.is_unique IS '是否唯一';
COMMENT ON COLUMN gen_table_column.python_type IS 'Python类型';
COMMENT ON COLUMN gen_table_column.python_field IS 'Python字段名';
COMMENT ON COLUMN gen_table_column.is_insert IS '是否为新增字段';
COMMENT ON COLUMN gen_table_column.is_edit IS '是否编辑字段';
COMMENT ON COLUMN gen_table_column.is_list IS '是否列表字段';
COMMENT ON COLUMN gen_table_column.is_query IS '是否查询字段';
COMMENT ON COLUMN gen_table_column.query_type IS '查询方式';
COMMENT ON COLUMN gen_table_column.html_type IS '显示类型';
COMMENT ON COLUMN gen_table_column.dict_type IS '字典类型';
COMMENT ON COLUMN gen_table_column.sort IS '排序';
COMMENT ON COLUMN gen_table_column.table_id IS '归属表编号';
COMMENT ON COLUMN gen_table_column.id IS '主键ID';
COMMENT ON COLUMN gen_table_column.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN gen_table_column.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN gen_table_column.description IS '备注/描述';
COMMENT ON COLUMN gen_table_column.created_time IS '创建时间';
COMMENT ON COLUMN gen_table_column.updated_time IS '更新时间';
COMMENT ON COLUMN gen_table_column.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN gen_table_column.deleted_time IS '删除时间';
COMMENT ON COLUMN gen_table_column.created_id IS '创建人ID';
COMMENT ON COLUMN gen_table_column.updated_id IS '更新人ID';
COMMENT ON COLUMN gen_table_column.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS gen_demo;
CREATE TABLE IF NOT EXISTS gen_demo (
  name varchar(64) NOT NULL,
  a integer DEFAULT NULL,
  b bigint DEFAULT NULL,
  c real DEFAULT NULL,
  d smallint NOT NULL DEFAULT 0,
  e date DEFAULT NULL,
  f time DEFAULT NULL,
  g timestamp DEFAULT NULL,
  h text,
  i jsonb DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT gen_demo_pkey PRIMARY KEY (id),
  CONSTRAINT ix_gen_demo_uuid UNIQUE (uuid),
  CONSTRAINT gen_demo_ibfk_1 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT gen_demo_ibfk_2 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT gen_demo_ibfk_3 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_gen_demo_updated_id ON gen_demo (updated_id);
CREATE INDEX IF NOT EXISTS ix_gen_demo_updated_time ON gen_demo (updated_time);
CREATE INDEX IF NOT EXISTS ix_gen_demo_is_deleted ON gen_demo (is_deleted);
CREATE INDEX IF NOT EXISTS ix_gen_demo_status ON gen_demo (status);
CREATE INDEX IF NOT EXISTS ix_gen_demo_deleted_id ON gen_demo (deleted_id);
CREATE INDEX IF NOT EXISTS ix_gen_demo_created_time ON gen_demo (created_time);
CREATE INDEX IF NOT EXISTS ix_gen_demo_deleted_time ON gen_demo (deleted_time);
CREATE INDEX IF NOT EXISTS ix_gen_demo_created_id ON gen_demo (created_id);
COMMENT ON TABLE gen_demo IS '示例表';
COMMENT ON COLUMN gen_demo.name IS '名称';
COMMENT ON COLUMN gen_demo.a IS '整数';
COMMENT ON COLUMN gen_demo.b IS '大整数';
COMMENT ON COLUMN gen_demo.c IS '浮点数';
COMMENT ON COLUMN gen_demo.d IS '布尔型';
COMMENT ON COLUMN gen_demo.e IS '日期';
COMMENT ON COLUMN gen_demo.f IS '时间';
COMMENT ON COLUMN gen_demo.g IS '日期时间';
COMMENT ON COLUMN gen_demo.h IS '长文本';
COMMENT ON COLUMN gen_demo.i IS '元数据(JSON格式)';
COMMENT ON COLUMN gen_demo.id IS '主键ID';
COMMENT ON COLUMN gen_demo.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN gen_demo.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN gen_demo.description IS '备注/描述';
COMMENT ON COLUMN gen_demo.created_time IS '创建时间';
COMMENT ON COLUMN gen_demo.updated_time IS '更新时间';
COMMENT ON COLUMN gen_demo.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN gen_demo.deleted_time IS '删除时间';
COMMENT ON COLUMN gen_demo.created_id IS '创建人ID';
COMMENT ON COLUMN gen_demo.updated_id IS '更新人ID';
COMMENT ON COLUMN gen_demo.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS gen_demo01;
CREATE TABLE IF NOT EXISTS gen_demo01 (
  name varchar(64) NOT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT gen_demo01_pkey PRIMARY KEY (id),
  CONSTRAINT ix_gen_demo01_uuid UNIQUE (uuid),
  CONSTRAINT gen_demo01_ibfk_1 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT gen_demo01_ibfk_2 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT gen_demo01_ibfk_3 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_gen_demo01_deleted_time ON gen_demo01 (deleted_time);
CREATE INDEX IF NOT EXISTS ix_gen_demo01_updated_time ON gen_demo01 (updated_time);
CREATE INDEX IF NOT EXISTS ix_gen_demo01_deleted_id ON gen_demo01 (deleted_id);
CREATE INDEX IF NOT EXISTS ix_gen_demo01_is_deleted ON gen_demo01 (is_deleted);
CREATE INDEX IF NOT EXISTS ix_gen_demo01_created_time ON gen_demo01 (created_time);
CREATE INDEX IF NOT EXISTS ix_gen_demo01_updated_id ON gen_demo01 (updated_id);
CREATE INDEX IF NOT EXISTS ix_gen_demo01_created_id ON gen_demo01 (created_id);
CREATE INDEX IF NOT EXISTS ix_gen_demo01_status ON gen_demo01 (status);
COMMENT ON TABLE gen_demo01 IS '示例1表';
COMMENT ON COLUMN gen_demo01.name IS '名称';
COMMENT ON COLUMN gen_demo01.id IS '主键ID';
COMMENT ON COLUMN gen_demo01.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN gen_demo01.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN gen_demo01.description IS '备注/描述';
COMMENT ON COLUMN gen_demo01.created_time IS '创建时间';
COMMENT ON COLUMN gen_demo01.updated_time IS '更新时间';
COMMENT ON COLUMN gen_demo01.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN gen_demo01.deleted_time IS '删除时间';
COMMENT ON COLUMN gen_demo01.created_id IS '创建人ID';
COMMENT ON COLUMN gen_demo01.updated_id IS '更新人ID';
COMMENT ON COLUMN gen_demo01.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS task_workflow_node_type;
CREATE TABLE IF NOT EXISTS task_workflow_node_type (
  name varchar(128) NOT NULL,
  code varchar(64) NOT NULL,
  category varchar(32) NOT NULL,
  func text NOT NULL,
  args text,
  kwargs text,
  sort_order integer NOT NULL,
  is_active smallint NOT NULL DEFAULT 0,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT task_workflow_node_type_pkey PRIMARY KEY (id),
  CONSTRAINT code UNIQUE (code),
  CONSTRAINT ix_task_workflow_node_type_uuid UNIQUE (uuid),
  CONSTRAINT task_workflow_node_type_ibfk_1 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT task_workflow_node_type_ibfk_2 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT task_workflow_node_type_ibfk_3 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_task_workflow_node_type_updated_time ON task_workflow_node_type (updated_time);
CREATE INDEX IF NOT EXISTS ix_task_workflow_node_type_created_id ON task_workflow_node_type (created_id);
CREATE INDEX IF NOT EXISTS ix_task_workflow_node_type_status ON task_workflow_node_type (status);
CREATE INDEX IF NOT EXISTS ix_task_workflow_node_type_updated_id ON task_workflow_node_type (updated_id);
CREATE INDEX IF NOT EXISTS ix_task_workflow_node_type_deleted_id ON task_workflow_node_type (deleted_id);
CREATE INDEX IF NOT EXISTS ix_task_workflow_node_type_is_deleted ON task_workflow_node_type (is_deleted);
CREATE INDEX IF NOT EXISTS ix_task_workflow_node_type_deleted_time ON task_workflow_node_type (deleted_time);
CREATE INDEX IF NOT EXISTS ix_task_workflow_node_type_created_time ON task_workflow_node_type (created_time);
COMMENT ON TABLE task_workflow_node_type IS '工作流编排节点类型（非定时任务节点）';
COMMENT ON COLUMN task_workflow_node_type.name IS '显示名称';
COMMENT ON COLUMN task_workflow_node_type.code IS '节点编码，对应画布 node.type';
COMMENT ON COLUMN task_workflow_node_type.category IS '分类: trigger/action/condition/control';
COMMENT ON COLUMN task_workflow_node_type.args IS '默认位置参数，逗号分隔';
COMMENT ON COLUMN task_workflow_node_type.kwargs IS '默认关键字参数 JSON';
COMMENT ON COLUMN task_workflow_node_type.sort_order IS '排序';
COMMENT ON COLUMN task_workflow_node_type.is_active IS '是否启用';
COMMENT ON COLUMN task_workflow_node_type.id IS '主键ID';
COMMENT ON COLUMN task_workflow_node_type.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN task_workflow_node_type.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN task_workflow_node_type.description IS '备注/描述';
COMMENT ON COLUMN task_workflow_node_type.created_time IS '创建时间';
COMMENT ON COLUMN task_workflow_node_type.updated_time IS '更新时间';
COMMENT ON COLUMN task_workflow_node_type.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN task_workflow_node_type.deleted_time IS '删除时间';
COMMENT ON COLUMN task_workflow_node_type.created_id IS '创建人ID';
COMMENT ON COLUMN task_workflow_node_type.updated_id IS '更新人ID';
COMMENT ON COLUMN task_workflow_node_type.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS task_workflow;
CREATE TABLE IF NOT EXISTS task_workflow (
  name varchar(128) NOT NULL,
  code varchar(64) NOT NULL,
  workflow_status varchar(32) NOT NULL,
  nodes jsonb DEFAULT NULL,
  edges jsonb DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT task_workflow_pkey PRIMARY KEY (id),
  CONSTRAINT uq_task_workflow_code UNIQUE (code),
  CONSTRAINT ix_task_workflow_uuid UNIQUE (uuid),
  CONSTRAINT task_workflow_ibfk_1 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT task_workflow_ibfk_2 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT task_workflow_ibfk_3 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_task_workflow_updated_id ON task_workflow (updated_id);
CREATE INDEX IF NOT EXISTS ix_task_workflow_is_deleted ON task_workflow (is_deleted);
CREATE INDEX IF NOT EXISTS ix_task_workflow_created_time ON task_workflow (created_time);
CREATE INDEX IF NOT EXISTS ix_task_workflow_updated_time ON task_workflow (updated_time);
CREATE INDEX IF NOT EXISTS ix_task_workflow_deleted_time ON task_workflow (deleted_time);
CREATE INDEX IF NOT EXISTS ix_task_workflow_status ON task_workflow (status);
CREATE INDEX IF NOT EXISTS ix_task_workflow_created_id ON task_workflow (created_id);
CREATE INDEX IF NOT EXISTS ix_task_workflow_deleted_id ON task_workflow (deleted_id);
COMMENT ON TABLE task_workflow IS '工作流定义表';
COMMENT ON COLUMN task_workflow.name IS '流程名称';
COMMENT ON COLUMN task_workflow.code IS '流程编码';
COMMENT ON COLUMN task_workflow.workflow_status IS '流程状态: draft/published/archived';
COMMENT ON COLUMN task_workflow.nodes IS 'Vue Flow nodes JSON';
COMMENT ON COLUMN task_workflow.edges IS 'Vue Flow edges JSON';
COMMENT ON COLUMN task_workflow.id IS '主键ID';
COMMENT ON COLUMN task_workflow.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN task_workflow.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN task_workflow.description IS '备注/描述';
COMMENT ON COLUMN task_workflow.created_time IS '创建时间';
COMMENT ON COLUMN task_workflow.updated_time IS '更新时间';
COMMENT ON COLUMN task_workflow.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN task_workflow.deleted_time IS '删除时间';
COMMENT ON COLUMN task_workflow.created_id IS '创建人ID';
COMMENT ON COLUMN task_workflow.updated_id IS '更新人ID';
COMMENT ON COLUMN task_workflow.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS task_job;
CREATE TABLE IF NOT EXISTS task_job (
  job_id varchar(64) NOT NULL,
  job_name varchar(128) DEFAULT NULL,
  trigger_type varchar(32) DEFAULT NULL,
  status varchar(16) NOT NULL,
  next_run_time varchar(64) DEFAULT NULL,
  job_state text,
  result text,
  error text,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  CONSTRAINT task_job_pkey PRIMARY KEY (id),
  CONSTRAINT ix_task_job_uuid UNIQUE (uuid)
);
CREATE INDEX IF NOT EXISTS ix_task_job_deleted_time ON task_job (deleted_time);
CREATE INDEX IF NOT EXISTS ix_task_job_created_time ON task_job (created_time);
CREATE INDEX IF NOT EXISTS ix_task_job_is_deleted ON task_job (is_deleted);
CREATE INDEX IF NOT EXISTS ix_task_job_job_id ON task_job (job_id);
CREATE INDEX IF NOT EXISTS ix_task_job_updated_time ON task_job (updated_time);
COMMENT ON TABLE task_job IS '任务执行日志表';
COMMENT ON COLUMN task_job.job_id IS '任务ID';
COMMENT ON COLUMN task_job.job_name IS '任务名称';
COMMENT ON COLUMN task_job.trigger_type IS '触发方式: cron/interval/date/manual';
COMMENT ON COLUMN task_job.status IS '执行状态';
COMMENT ON COLUMN task_job.next_run_time IS '下次执行时间';
COMMENT ON COLUMN task_job.job_state IS '任务状态信息';
COMMENT ON COLUMN task_job.result IS '执行结果';
COMMENT ON COLUMN task_job.error IS '错误信息';
COMMENT ON COLUMN task_job.id IS '主键ID';
COMMENT ON COLUMN task_job.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN task_job.description IS '备注/描述';
COMMENT ON COLUMN task_job.created_time IS '创建时间';
COMMENT ON COLUMN task_job.updated_time IS '更新时间';
COMMENT ON COLUMN task_job.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN task_job.deleted_time IS '删除时间';

DROP TABLE IF EXISTS task_node;
CREATE TABLE IF NOT EXISTS task_node (
  name varchar(64) NOT NULL,
  code varchar(32) NOT NULL,
  jobstore varchar(64) DEFAULT NULL,
  executor varchar(64) DEFAULT NULL,
  trigger varchar(64) DEFAULT NULL,
  trigger_args text,
  func text,
  args text,
  kwargs text,
  coalesce smallint DEFAULT NULL,
  max_instances integer DEFAULT NULL,
  start_date varchar(64) DEFAULT NULL,
  end_date varchar(64) DEFAULT NULL,
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid varchar(64) NOT NULL,
  status varchar(10) NOT NULL,
  description text,
  created_time timestamp NOT NULL,
  updated_time timestamp NOT NULL,
  is_deleted smallint NOT NULL DEFAULT 0,
  deleted_time timestamp DEFAULT NULL,
  created_id integer DEFAULT NULL,
  updated_id integer DEFAULT NULL,
  deleted_id integer DEFAULT NULL,
  CONSTRAINT task_node_pkey PRIMARY KEY (id),
  CONSTRAINT code UNIQUE (code),
  CONSTRAINT ix_task_node_uuid UNIQUE (uuid),
  CONSTRAINT task_node_ibfk_1 FOREIGN KEY (created_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT task_node_ibfk_2 FOREIGN KEY (updated_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT task_node_ibfk_3 FOREIGN KEY (deleted_id) REFERENCES sys_user(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_task_node_updated_id ON task_node (updated_id);
CREATE INDEX IF NOT EXISTS ix_task_node_updated_time ON task_node (updated_time);
CREATE INDEX IF NOT EXISTS ix_task_node_is_deleted ON task_node (is_deleted);
CREATE INDEX IF NOT EXISTS ix_task_node_status ON task_node (status);
CREATE INDEX IF NOT EXISTS ix_task_node_deleted_id ON task_node (deleted_id);
CREATE INDEX IF NOT EXISTS ix_task_node_created_time ON task_node (created_time);
CREATE INDEX IF NOT EXISTS ix_task_node_deleted_time ON task_node (deleted_time);
CREATE INDEX IF NOT EXISTS ix_task_node_created_id ON task_node (created_id);
COMMENT ON TABLE task_node IS '节点类型表';
COMMENT ON COLUMN task_node.name IS '节点名称';
COMMENT ON COLUMN task_node.code IS '节点编码';
COMMENT ON COLUMN task_node.jobstore IS '存储器';
COMMENT ON COLUMN task_node.executor IS '执行器';
COMMENT ON COLUMN task_node.trigger IS '触发器';
COMMENT ON COLUMN task_node.trigger_args IS '触发器参数';
COMMENT ON COLUMN task_node.func IS '代码块';
COMMENT ON COLUMN task_node.args IS '位置参数';
COMMENT ON COLUMN task_node.kwargs IS '关键字参数';
COMMENT ON COLUMN task_node.coalesce IS '是否合并运行';
COMMENT ON COLUMN task_node.max_instances IS '最大实例数';
COMMENT ON COLUMN task_node.start_date IS '开始时间';
COMMENT ON COLUMN task_node.end_date IS '结束时间';
COMMENT ON COLUMN task_node.id IS '主键ID';
COMMENT ON COLUMN task_node.uuid IS 'UUID全局唯一标识';
COMMENT ON COLUMN task_node.status IS '状态(0:正常 1:禁用)';
COMMENT ON COLUMN task_node.description IS '备注/描述';
COMMENT ON COLUMN task_node.created_time IS '创建时间';
COMMENT ON COLUMN task_node.updated_time IS '更新时间';
COMMENT ON COLUMN task_node.is_deleted IS '是否已删除(0:未删除 1:已删除)';
COMMENT ON COLUMN task_node.deleted_time IS '删除时间';
COMMENT ON COLUMN task_node.created_id IS '创建人ID';
COMMENT ON COLUMN task_node.updated_id IS '更新人ID';
COMMENT ON COLUMN task_node.deleted_id IS '删除人ID';

DROP TABLE IF EXISTS agno_schema_versions;
CREATE TABLE IF NOT EXISTS agno_schema_versions (
  table_name varchar(128) NOT NULL,
  version varchar(10) NOT NULL,
  created_at varchar(128) NOT NULL,
  updated_at varchar(128) DEFAULT NULL,
  CONSTRAINT agno_schema_versions_pkey PRIMARY KEY (table_name)
);
CREATE INDEX IF NOT EXISTS idx_agno_schema_versions_created_at ON agno_schema_versions (created_at);

DROP TABLE IF EXISTS agno_sessions;
CREATE TABLE IF NOT EXISTS agno_sessions (
  session_id varchar(128) NOT NULL,
  session_type varchar(20) NOT NULL,
  agent_id varchar(128) DEFAULT NULL,
  team_id varchar(128) DEFAULT NULL,
  workflow_id varchar(128) DEFAULT NULL,
  user_id varchar(128) DEFAULT NULL,
  session_data jsonb DEFAULT NULL,
  agent_data jsonb DEFAULT NULL,
  team_data jsonb DEFAULT NULL,
  workflow_data jsonb DEFAULT NULL,
  metadata jsonb DEFAULT NULL,
  runs jsonb DEFAULT NULL,
  summary jsonb DEFAULT NULL,
  created_at bigint NOT NULL,
  updated_at bigint DEFAULT NULL,
  CONSTRAINT agno_sessions_pkey PRIMARY KEY (session_id)
);
CREATE INDEX IF NOT EXISTS idx_agno_sessions_created_at ON agno_sessions (created_at);
CREATE INDEX IF NOT EXISTS idx_agno_sessions_session_type ON agno_sessions (session_type);

DROP TABLE IF EXISTS apscheduler_jobs;
CREATE TABLE IF NOT EXISTS apscheduler_jobs (
  id varchar(191) NOT NULL,
  next_run_time double precision DEFAULT NULL,
  job_state bytea NOT NULL,
  CONSTRAINT apscheduler_jobs_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_apscheduler_jobs_next_run_time ON apscheduler_jobs (next_run_time);

DROP TABLE IF EXISTS alembic_version;
CREATE TABLE IF NOT EXISTS alembic_version (
  version_num varchar(32) NOT NULL,
  CONSTRAINT alembic_version_pkey PRIMARY KEY (version_num)
);
