"""add id_card to sys_user

Revision ID: 34a1c8187ef6
Revises: 1add412124be
Create Date: 2026-07-21 13:20:01.259755

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34a1c8187ef6'
down_revision: str | None = '1add412124be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否主键',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否查询字段',
               existing_nullable=False)
    op.add_column('sys_user', sa.Column('id_card', sa.String(length=255), nullable=True, comment='身份证号(SM4加密)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'id_card')
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否查询字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否主键',
               existing_nullable=False)
    # ### end Alembic commands ###
