"""Strategy-application catalog metadata for Web UI (honest capability levels)."""

from __future__ import annotations

from typing import Any

# wiring:
#   wired     — useful REST/UI against real engine APIs
#   status    — engine load + status / light hooks only
#   link      — points at existing product surface
#   na        — not applicable on this stack (do not add_app)
#   optional  — package often missing / platform-limited

CATALOG: list[dict[str, Any]] = [
    {
        "key": "cta",
        "title": "CTA自动交易",
        "package": "vnpy_ctastrategy",
        "class_name": "CtaStrategyApp",
        "app_name": "CtaStrategy",
        "wiring": "wired",
        "summary": "列出/初始化/启停 CTA 策略实例（依赖引擎已加载）。",
        "loadable": True,
    },
    {
        "key": "backtester",
        "title": "CTA回测研究",
        "package": "vnpy_ctabacktester",
        "class_name": "CtaBacktesterApp",
        "app_name": "CtaBacktester",
        "wiring": "wired",
        "summary": "启动回测线程并查询统计结果（需历史数据）。",
        "loadable": True,
    },
    {
        "key": "spread",
        "title": "多合约价差套利",
        "package": "vnpy_spreadtrading",
        "class_name": "SpreadTradingApp",
        "app_name": "SpreadTrading",
        "wiring": "status",
        "summary": "引擎加载与启停；价差腿配置仍以 vnpy 侧设置为准。",
        "loadable": True,
    },
    {
        "key": "option",
        "title": "期权波动率交易",
        "package": "vnpy_optionmaster",
        "class_name": "OptionMasterApp",
        "app_name": "OptionMaster",
        "wiring": "status",
        "summary": "引擎与组合名查询；不虚构定价/盈亏。",
        "loadable": True,
    },
    {
        "key": "portfolio",
        "title": "多合约组合策略",
        "package": "vnpy_portfoliostrategy",
        "class_name": "PortfolioStrategyApp",
        "app_name": "PortfolioStrategy",
        "wiring": "status",
        "summary": "策略类列表与启停钩子（若引擎已加载）。",
        "loadable": True,
    },
    {
        "key": "algo",
        "title": "算法委托执行",
        "package": "vnpy_algotrading",
        "class_name": "AlgoTradingApp",
        "app_name": "AlgoTrading",
        "wiring": "wired",
        "summary": "算法模板与运行中算法列表/停止。",
        "loadable": True,
    },
    {
        "key": "script",
        "title": "脚本策略交易",
        "package": "vnpy_scripttrader",
        "class_name": "ScriptTraderApp",
        "app_name": "ScriptTrader",
        "wiring": "status",
        "summary": "脚本引擎已挂载；策略文件仍在本地 scripts 目录管理。",
        "loadable": True,
    },
    {
        "key": "paper",
        "title": "本地仿真交易",
        "package": "vnpy_paperaccount",
        "class_name": "PaperAccountApp",
        "app_name": "PaperAccount",
        "wiring": "wired",
        "summary": "查看/调整滑点、即时成交与定时撮合间隔。",
        "loadable": True,
    },
    {
        "key": "recorder",
        "title": "实盘行情记录",
        "package": "vnpy_datarecorder",
        "class_name": "DataRecorderApp",
        "app_name": "DataRecorder",
        "wiring": "wired",
        "summary": "Tick/Bar 录制合约增删与当前列表。",
        "loadable": True,
    },
    {
        "key": "datamanager",
        "title": "历史数据管理",
        "package": "vnpy_datamanager",
        "class_name": "DataManagerApp",
        "app_name": "DataManager",
        "wiring": "wired",
        "summary": "数据库 Bar 概览（依赖 vnpy database 配置）。",
        "loadable": True,
    },
    {
        "key": "risk",
        "title": "事前风控",
        "package": "vnpy_riskmanager",
        "class_name": "RiskManagerApp",
        "app_name": "RiskManager",
        "wiring": "wired",
        "summary": "已加载规则列表与规则数据（会 patch 下单路径）。",
        "loadable": True,
    },
    {
        "key": "rpc",
        "title": "RPC服务器",
        "package": "vnpy_rpcservice",
        "class_name": "RpcServiceApp",
        "app_name": "RpcService",
        "wiring": "wired",
        "summary": "启停 REP/PUB 地址；默认未自动监听。",
        "loadable": True,
    },
    {
        "key": "chart",
        "title": "实时K线图表",
        "package": "vnpy_chartwizard",
        "class_name": "ChartWizardApp",
        "app_name": "ChartWizard",
        "wiring": "link",
        "summary": "引擎可加载；产品内请用行情中心 QuoteChart（含 MACD）。",
        "loadable": True,
        "link_path": "/market/quotes",
    },
    {
        "key": "portfolio_mgr",
        "title": "投资组合管理",
        "package": "vnpy_portfoliomanager",
        "class_name": "PortfolioManagerApp",
        "app_name": "PortfolioManager",
        "wiring": "status",
        "summary": "组合结果查询钩子；不虚构盈亏曲线。",
        "loadable": True,
    },
    {
        "key": "excelrtd",
        "title": "EXCEL RTD",
        "package": "vnpy_excelrtd",
        "class_name": "ExcelRtdApp",
        "app_name": "ExcelRtd",
        "wiring": "optional",
        "summary": "Windows + Excel COM 专用；macOS/Linux 通常无法安装或运行。",
        "loadable": True,
        "platform_note": "windows-only",
    },
    {
        "key": "webtrader",
        "title": "Web服务器",
        "package": "vnpy_webtrader",
        "class_name": "WebTraderApp",
        "app_name": "RpcService",
        "wiring": "na",
        "summary": "本项目已是 FastAPI + Vue Web 交易台；不二次加载官方 WebTrader（与 RpcService 的 app_name 冲突）。",
        "loadable": False,
        "link_path": "/health",
    },
]

CATALOG_BY_KEY = {item["key"]: item for item in CATALOG}
